---
apiVersion: v1
kind: Namespace
metadata:
  name: home-automation
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-config
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-data
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-data
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasmo-data
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

#################################################################
#                         HOME ASSISTANT                        #
#################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:stable
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /config
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: dbus
              mountPath: /run/dbus
              readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: hass-config
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: dbus
          hostPath:
            path: /run/dbus
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-ui
  namespace: home-automation
  annotations:
    metallb.universe.tf/allow-shared-ip: ha-shared
spec:
  type: LoadBalancer
  loadBalancerIP: 10.100.99.123
  ports:
    - name: homeassistant
      port: 8123
      targetPort: 8123
      protocol: TCP
  selector:
    app: homeassistant

#################################################################
#                          MOSQUITTO                            #
#################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
        - name: mqtt
          image: eclipse-mosquitto
          volumeMounts:
            - name: mqtt-data
              mountPath: /mosquitto
      volumes:
        - name: mqtt-data
          persistentVolumeClaim:
            claimName: mqtt-data

---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: home-automation
  annotations:
    metallb.universe.tf/allow-shared-ip: ha-shared
spec:
  selector:
    app: mqtt
  type: LoadBalancer
  loadBalancerIP: 10.100.99.123
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: ws

#################################################################
#                        ZIGBEE2MQTT                            #
#################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:latest
          env:
            - name: TZ
              value: Europe/Bucharest
          volumeMounts:
            - name: zigbee-data
              mountPath: /app/data
            - name: udev
              mountPath: /run/udev
              readOnly: true
      volumes:
        - name: zigbee-data
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data
        - name: udev
          hostPath:
            path: /run/udev

---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  namespace: home-automation
  annotations:
    metallb.universe.tf/allow-shared-ip: ha-shared
spec:
  selector:
    app: zigbee2mqtt
  type: LoadBalancer
  loadBalancerIP: 10.100.99.123
  ports:
    - port: 8080
      targetPort: 8080

#################################################################
#                            ESPHOME                            #
#################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esphome
  template:
    metadata:
      labels:
        app: esphome
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: esphome
          image: esphome/esphome:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: esphome-config
              mountPath: /config
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: esphome-config
          persistentVolumeClaim:
            claimName: esphome-config
        - name: localtime
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: esphome-ui
  namespace: home-automation
  annotations:
    metallb.universe.tf/allow-shared-ip: ha-shared
spec:
  type: LoadBalancer
  loadBalancerIP: 10.100.99.123
  ports:
    - name: esphome
      port: 6052
      targetPort: 6052
      protocol: TCP
  selector:
    app: esphome

#################################################################
#                         MATTER SERVER                         #
#################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matter-server
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsNonRoot: false
      containers:
        - name: matter-server
          image: ghcr.io/home-assistant-libs/python-matter-server:stable
          securityContext:
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: matter-data
              mountPath: /data
            - name: dbus
              mountPath: /run/dbus
              readOnly: true
      volumes:
        - name: matter-data
          persistentVolumeClaim:
            claimName: matter-data
        - name: dbus
          hostPath:
            path: /run/dbus
---
apiVersion: v1
kind: Service
metadata:
  name: matter-server-ui
  namespace: home-automation
  annotations:
    metallb.universe.tf/allow-shared-ip: ha-shared
spec:
  type: LoadBalancer
  loadBalancerIP: 10.100.99.123
  ports:
    - name: matter
      port: 5580
      targetPort: 5580
      protocol: TCP
  selector:
    app: matter-server

#################################################################
#                         TASMOADMIN                            #
#################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasmo-admin
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasmo-admin
  template:
    metadata:
      labels:
        app: tasmo-admin
    spec:
      containers:
        - name: tasmo-admin
          image: ghcr.io/tasmoadmin/tasmoadmin:latest
          volumeMounts:
            - name: tasmo-data
              mountPath: /data
      volumes:
        - name: tasmo-data
          persistentVolumeClaim:
            claimName: tasmo-data

---
apiVersion: v1
kind: Service
metadata:
  name: tasmo-admin
  namespace: home-automation
  annotations:
    metallb.universe.tf/allow-shared-ip: ha-shared
spec:
  selector:
    app: tasmo-admin
  type: LoadBalancer
  loadBalancerIP: 10.100.99.123
  ports:
    - port: 8082
      targetPort: 80